# Generated by Django 2.2.1 on 2019-06-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agravos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agravos.notificaodengue',),
        ),
    ]
