# Generated by Django 2.2.1 on 2019-06-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Agravo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agravo', models.CharField(choices=[('Hanseniase', 'Hanseniase'), ('Dengue', 'Dengue'), ('Tuberculose', 'Tuberculose')], default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Agravo',
                'verbose_name_plural': 'Tipos de Agravos',
            },
        ),
    ]
