# Generated by Django 2.2.1 on 2019-05-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agravos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_agravo',
            options={'verbose_name': 'Tipo de Agravo', 'verbose_name_plural': 'Tipos de Agravos'},
        ),
        migrations.AddField(
            model_name='tipo_agravo',
            name='agravo',
            field=models.CharField(choices=[('Hanseniese', 'Hanseniese'), ('Dengue', 'Dengue'), ('Tuberculose', 'Tuberculose')], default='', max_length=100),
        ),
    ]
