# Generated by Django 2.2.1 on 2019-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agravos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doencas',
            options={'verbose_name': 'Doença', 'verbose_name_plural': 'Doenças'},
        ),
        migrations.AddField(
            model_name='notificaodengue',
            name='exames',
            field=models.ManyToManyField(to='agravos.Exames'),
        ),
    ]
