# Generated by Django 2.2.1 on 2019-06-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agravos', '0002_auto_20190628_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaodengue',
            name='exames',
        ),
        migrations.AddField(
            model_name='notificaodengue',
            name='exames',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agravos.Exames'),
            preserve_default=False,
        ),
    ]
