# Generated by Django 2.2.1 on 2019-06-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agravos', '0004_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agravos.Exames'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
