# Generated by Django 2.2.1 on 2019-06-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agravos', '0005_auto_20190628_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaodengue',
            name='exames',
        ),
    ]
