# Generated by Django 2.2.1 on 2019-06-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agravos', '0008_auto_20190628_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaodengue',
            name='resul_segunda_coleta',
        ),
    ]
