# Generated by Django 2.2.1 on 2019-06-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo_ibge', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo_ibge', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_de_Saude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=10)),
                ('pais', models.CharField(blank=True, max_length=500)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_cidade', to='core.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_estado', to='core.Estado')),
            ],
            options={
                'verbose_name': 'Unidade de Saúde',
                'verbose_name_plural': 'Unidades de Saúde',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=500)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('IGNORADO', 'Ignorado')], max_length=50)),
                ('gestante', models.CharField(choices=[('1° TRIMESTE', '1° Trimestre '), ('2° TRIMESTE', '2° Trimestre'), ('3° TRIMESTE', '3° Trimestre'), ('IDADE GESTACIONAL IGNORADA', 'Idade Gestacional Ignorada'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se Aplica'), ('IGNORADO', 'Ignorado')], max_length=50)),
                ('raca', models.CharField(choices=[('NEGRA', 'Negra'), ('BRANCA', 'Branca'), ('PARDA', 'Parda'), ('INDIGENA', 'Indigena')], max_length=50)),
                ('escolaridade', models.CharField(choices=[('FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO_MEDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MEDIO COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR INCOMPLETO', 'Educação Superior Incompleto'), ('SUPERIOR COMPLETO', 'Educação Superior Completa'), ('IGNORADO', 'Ignorado'), ('NÃO SE APLICA', 'Não se aplica')], max_length=50)),
                ('numero_carta_sus', models.CharField(max_length=15)),
                ('nome_da_mae', models.CharField(blank=True, max_length=500)),
                ('distrito', models.CharField(max_length=500)),
                ('bairro', models.CharField(max_length=500)),
                ('rua', models.CharField(max_length=500)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('ponto_referencia', models.CharField(max_length=500)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(max_length=50)),
                ('zona', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural'), ('PERIURBANA', 'Periurbana'), ('IGNORADO', 'Ignorado')], max_length=50)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_cidade', to='core.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=500)),
                ('rua', models.CharField(max_length=500)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cidade', to='core.Estado')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_estado', to='core.Estado'),
        ),
    ]
