# Generated by Django 2.2.1 on 2019-05-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=500)),
                ('rua', models.CharField(max_length=500)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
