# Generated by Django 2.2.1 on 2019-06-01 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=500)),
                ('rua', models.CharField(max_length=500)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('codigo_ibge', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_de_Saude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=500)),
                ('telefone', models.CharField(max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('IGNORADO', 'Ignorado')], max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('raca', models.CharField(blank=True, choices=[('NEGRA', 'Negra'), ('BRANCA', 'Branca'), ('PARDA', 'Parda'), ('INDIGENA', 'Indigena')], max_length=50, null=True)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_endereco', to='core.Endereco', unique=True)),
            ],
        ),
    ]
