# Generated by Django 2.2.1 on 2019-05-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_endereco', to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMEM', 'Homem'), ('MULHER', 'Mulher')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
