# Generated by Django 2.2.1 on 2019-06-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Paciente',
        ),
    ]
