# Generated by Django 2.2.1 on 2019-06-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190601_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo_ibge', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='codigo_ibge',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_cidade', to='core.Estado'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo_ibge', models.CharField(max_length=80)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidade_estado', to='core.Estado')),
            ],
        ),
    ]
