# Generated by Django 2.2.1 on 2019-06-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190601_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade_de_saude',
            options={'verbose_name': 'Unidade de Saúde', 'verbose_name_plural': 'Unidades de Saúde'},
        ),
        migrations.AddField(
            model_name='unidade_de_saude',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidade_cidade', to='core.Cidade'),
        ),
        migrations.AddField(
            model_name='unidade_de_saude',
            name='codigo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidade_de_saude',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidade_estado', to='core.Estado'),
        ),
        migrations.AddField(
            model_name='unidade_de_saude',
            name='nome',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
