# Generated by Django 2.2.1 on 2019-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190624_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_da_mae',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_carta_sus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.CharField(blank=True, choices=[('NEGRA', 'Negra'), ('BRANCA', 'Branca'), ('PARDA', 'Parda'), ('INDIGENA', 'Indigena')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidade_de_saude',
            name='pais',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
