# Generated by Django 2.2.1 on 2019-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190624_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='gestante',
            field=models.CharField(blank=True, choices=[('1° TRIMESTE', '1° Trimestre '), ('2° TRIMESTE', '2° Trimestre'), ('3° TRIMESTE', '3° Trimestre'), ('IDADE GESTACIONAL IGNORADA', 'Idade Gestacional Ignorada'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se Aplica'), ('IGNORADO', 'Ignorado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='zona',
            field=models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural'), ('PERIURBANA', 'Periurbana'), ('IGNORADO', 'Ignorado')], max_length=50, null=True),
        ),
    ]
