# Generated by Django 2.2.1 on 2019-06-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190624_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_estado', to='core.Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cidade', to='core.Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_cidade', to='core.Cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(choices=[('FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO_MEDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MEDIO COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR INCOMPLETO', 'Educação Superior Incompleto'), ('SUPERIOR COMPLETO', 'Educação Superior Completa'), ('IGNORADO', 'Ignorado'), ('NÃO SE APLICA', 'Não se aplica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gestante',
            field=models.CharField(choices=[('1° TRIMESTE', '1° Trimestre '), ('2° TRIMESTE', '2° Trimestre'), ('3° TRIMESTE', '3° Trimestre'), ('IDADE GESTACIONAL IGNORADA', 'Idade Gestacional Ignorada'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se Aplica'), ('IGNORADO', 'Ignorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_carta_sus',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.CharField(choices=[('NEGRA', 'Negra'), ('BRANCA', 'Branca'), ('PARDA', 'Parda'), ('INDIGENA', 'Indigena')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('IGNORADO', 'Ignorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='zona',
            field=models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural'), ('PERIURBANA', 'Periurbana'), ('IGNORADO', 'Ignorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='unidade_de_saude',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_cidade', to='core.Cidade'),
        ),
        migrations.AlterField(
            model_name='unidade_de_saude',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_estado', to='core.Estado'),
        ),
    ]
